### ISSUE TITLE
does modelscope have a real upload action as huggingface-cli upload?

### ISSUE THREAD

**Issue by thxCode** [modelscope/modelscope#1139]
#### background
transfer model files from hugginface to modelscope.

#### questions
1. Does modelscope (as a CLI) have a subcommand like `huggingface-cli upload` instead of the ugly script from https://modelscope.cn/docs/models/upload?
2. Has Modelscope planned to replace Git LFS upload with another approach? It seems the `push_model` wasted lots of space and time.
<img width="1317" alt="image" src="https://github.com/user-attachments/assets/2dd78a4a-8d5b-44ad-87e2-a5ac44036134">

The above screenshot shows that the remaining 82G space cannot upload 41.47GB model files, does `push_model` copy model files to TMPDIR and Git LFS check-in again?

**Comment by yingdachen** [comment]
we are working on it...

**Comment by thxCode** [comment]
@yingdachen  any milestone?

**Comment by yingdachen** [comment]
> @yingdachen any milestone?

this is scheduled for our next release (early Jan).

**Comment by yingdachen** [comment]
> gpustack/gpustack#745

regarding this issue, with your permission, we can help sync all your models on huggingface to modelscope.

**Comment by thxCode** [comment]
> > [gpustack/gpustack#745](https://github.com/gpustack/gpustack/issues/745)
> 
> regarding this issue, with your permission, we can help sync all your models on huggingface to modelscope.

I had another trouble with the repo syncing. 

after I found this issue, I tried to reduce the size of the synchronized files each time. after I synchronized the `! *-pure-*` files under https://huggingface.co/gpustack/stable-diffusion-v3-medium-GGUF/tree/main to MS, I tried to synchronize the `*-pure-*` files for the second time, but this operation never succeeded: modelscope SDK seemed to use up all the resources of the machine, and I couldn't get any more information.

I am indeed disappointed with this synchronization operation, but fortunately you were able to respond and support here soon.

we hope to sync the repos from this HF collection https://huggingface.co/collections/gpustack/image-672dafeb2fa0d02dbe2539a9 to our [MS account](https://www.modelscope.cn/profile/gpustack).

can you help us synchronize the following repos?

<img width="894" alt="image" src="https://github.com/user-attachments/assets/29ef7efa-07fa-4953-9433-1fc809273d28" />

**Comment by yingdachen** [comment]
sorry for the late response, for uploading, currently modelscope SDK relies on git operations, and made some additionaly assumption(for example, all git temp filers were stored in /tmp/ folder, which we fixed recently in master branch)

at this moment, we would recommend using native git commands for model upload. the non-git-based uploading is currently in active development, we plan to make it available for our 1.22 release.

in the meantime, with your permission, we have synced all models in your gpustack account to modelscope, fyi.

https://modelscope.cn/profile/gpustack

**Comment by thxCode** [comment]
try with new release `modelscope-1.22.1-py3-none-any.whl`, it works on my Apple M1 Max., but raise an error when executing the following steps in Github Action Ubuntu 22.04 Runner.

first try with `modelscope login --token <my token> &&  modelscope upload <my-repo> . .`
```
Processing 37 items:   0%|          | 0.00/37.0 [00:00<?, ?it/s]
Processing 37 items:   3%|▎         | 1.00/37.0 [00:00<00:18, 1.92it/s]
Processing 37 items:   3%|▎         | 1.00/37.0 [00:03<01:56, 3.25s/it]
Traceback (most recent call last):
  File "/home/runner/.local/bin/modelscope", line 8, in <module>
    sys.exit(run_cmd())
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/cli/cli.py", line 47, in run_cmd
    cmd.execute()
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/cli/upload.py", line 165, in execute
    commit_info = api.upload_folder(
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/api.py", line 1462, in upload_folder
    uploaded_items_list = _upload_items(
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/utils/thread_utils.py", line 66, in wrapper
    results.append(future.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/api.py", line 1[44](https://github.com/gpustack/.github/actions/runs/12780499623/job/35627036257#step:5:45)7, in _upload_items
    upload_res: dict = self._upload_blob(
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/api.py", line 1531, in _upload_blob
    upload_objects = self._validate_blob(
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/api.py", line 16[46](https://github.com/gpustack/.github/actions/runs/12780499623/job/35627036257#step:5:47), in _validate_blob
    raise_on_error(resp)
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/errors.py", line 142, in raise_on_error
    raise RequestError(rsp['Message'])
modelscope.hub.errors.RequestError: user not logged in
```

change to `modelscope upload <my-repo> . . --token <my token>`
```
Processing 37 items:   0%|          | 0.00/37.0 [00:00<?, ?it/s]
Processing 37 items:   3%|▎         | 1.00/37.0 [00:00<00:18, 1.92it/s]
Processing 37 items:   3%|▎         | 1.00/37.0 [00:03<01:56, 3.25s/it]
Traceback (most recent call last):
  File "/home/runner/.local/bin/modelscope", line 8, in <module>
    sys.exit(run_cmd())
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/cli/cli.py", line 47, in run_cmd
    cmd.execute()
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/cli/upload.py", line 165, in execute
    commit_info = api.upload_folder(
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/api.py", line 1462, in upload_folder
    uploaded_items_list = _upload_items(
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/utils/thread_utils.py", line 66, in wrapper
    results.append(future.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/api.py", line 1447, in _upload_items
    upload_res: dict = self._upload_blob(
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/api.py", line 1531, in _upload_blob
    upload_objects = self._validate_blob(
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/api.py", line 1646, in _validate_blob
    raise_on_error(resp)
  File "/home/runner/.local/lib/python3.10/site-packages/modelscope/hub/errors.py", line 1[42](https://github.com/gpustack/.github/actions/runs/12780413892/job/35626631440#step:5:43), in raise_on_error
    raise RequestError(rsp['Message'])
modelscope.hub.errors.RequestError: user not logged in
```

**Comment by thxCode** [comment]
try with the new release `modelscope-1.22.1-py3-none-any.whl` in my Apple M1 Max, the `user not logged in` is gone, but I get a warning message and have to do it twice as a workaround.

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/691c44fd-2b54-49e3-b577-2b44818cebe2" />

**Comment by yingdachen** [comment]
this is due to asyn deployment of server side change, both problems (user login and dup file check) should have been fixed on the server side by now. please try again.

**Comment by wangxingjun778** [comment]
Fixed both issues (login on the notebook env, commit failed);   Pls install the latest version 1.22.2 and try again. (1.22.1 still available, but the latest version is recommended)  :)

**Comment by wangxingjun778** [comment]
Sorry for the bad experience ！

This sporadic issue has been resolved (merged to master branch). It was caused by the token expiration policy of the cloud firewall. 

Additionally, you can completely avoid this issue by using the command `modelscope upload xxx --token xxx-xxx`

If you have any further questions, feel free to discuss them at any time.  :)

**Comment by yingdachen** [comment]
> Sorry for the bad experience ！
> 
> This sporadic issue has been resolved (merged to master branch). It was caused by the token expiration policy of the cloud firewall.
> 
> Additionally, you can completely avoid this issue by using the command `modelscope upload xxx --token xxx-xxx`
> 
> If you have any further questions, feel free to discuss them at any time. :)

let me try to summarize:
1. please use upload with token command for now, not the login and then upload without token approach, which is still buggy as described above
2. the bug is fixed now in master branch and will be included in next release 1.22.3

**Comment by wangxingjun778** [comment]
Update:  the latest version v1.22.3 is already released.  Please run `pip install modelscope -U` to use it.

**Comment by thxCode** [comment]
@wangxingjun778 @yingdachen  Thanks, I have separated the upload files and made multiple uploads to achieve the goal. This issue can be closed and reopened if I find it again.
